routes/web.php
<?php
/*
  ./routes/web.php
  Routeur
*/


/*-----------------------------------
    CREATURES
-----------------------------------*/

Route::prefix('creatures')->name('creatures.')->group(function(){
  /*
    DETAILS D'UNE CREATURE
    PATERN: /creatures/{creature}/{slug}.html
    CTRL: CreaturesController
    ACTION: show
   */
  Route::get('{creature}/{slug}.html', 'CreaturesController@show')
         ->where([
                  'creature'   => '[1-9][0-9]*',
                  'slug' => '[a-z0-9][a-z0-9\-]*'
                ])
         ->name('show');

  /*
    RECHERCHE D'UNE CREATURE
    PATERN: /creatures/search
    CTRL: CreaturesController
    ACTION: search
   */
  Route::get('search', 'CreaturesController@search')->name('search');

});


/*-----------------------------------
    FILMS
-----------------------------------*/
Route::prefix('films')->name('films.')->group(function(){
/*
  DETAILS D'UN FILM
  PATTERN: /films/{film}/{slug}.html [GET]
  CTRL: Films
  ACTION: show
 */
Route::get('{film}/{slug}.html', 'FilmsController@show')
      ->where([
               'film'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('show');

/*
  FORMULAIRE D'AJOUT D'UN FILM
  PATTERN: /films/add [GET]
  CTRL: Films
  ACTION: add
 */
  Route::get('add','FilmsController@add')->name('add');

/*
  AJOUT D'UN FILM
  PATTERN: /films [POST]
  CTRL: Films
  ACTION: store
 */
Route::post('', 'FilmsController@store')->name('store');

/*
  EDITION D'UN FILM
  PATTERN: /films/{film}/{slug}/edit.html    [POST]
  CTRL: Films
  ACTION: edit
 */
Route::get('{film}/{slug}/edit.html', 'FilmsController@edit')
        ->where([
          'film' => '[1-9][0-9]*',
          'slug' => '[a-z0-9][a-z0-9\-]*'
        ])
        ->name('edit');

/*
  UPDATE D'UN FILM
  PATTERN: /films/id/slug.html [PATCH]
  CTRL: Films
  ACTION: update
 */
 Route::patch('/films/{film}/{slug}.html','FilmsController@update')
          ->where([
             'film' => '[1-9][0-9]*',
             'slug' => '[a-z0-9][a-z0-9\-]*'
            ])
         ->name('update');
/*
SUPPRESSION D'UN FILM
 PATTERN: /films/{film}/{slug} [DELETE]
 CTRL: Films
 ACTION: destroy
*/
Route::delete('/films/{film}/{slug}.html', 'FilmsController@destroy')
      ->where([
         'film' => '[1-9][0-9]*',
         'slug' => '[a-z0-9][a-z0-9\-]*'
        ])
      ->name('destroy');
});

/*-----------------------------------
    TAGS
-----------------------------------*/
/*
  DETAILS D'UN TAG
  PATTERN: /tags/{tag}/{slug}.html [GET]
  CTRL: Tags
  ACTION: show
 */
Route::get('/tags/{tag}/{slug}.html', 'TagsController@show')
      ->where([
               'tag'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('tags.show');

/*-----------------------------------
    PAGES
-----------------------------------*/
/*
 DETAILS D'UNE PAGE
 PATERN: /pages/{page}/{slug}.html
 CTRL: PagesController
 ACTION: show
*/
Route::get('/pages/{page}/{slug}.html', 'PagesController@show')
     ->where([
               'page'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('pages.show');

//==============================================================

/*
  MISE A DISPOSITION DE DONNEES POUR CERTAINES VUES
*/
View::composer('pages.menu', function($view){
  $view->with('pages', App\Http\Models\Page::all());
});

View::composer('tags.index', function($view){
  $view->with('tags', App\Http\Models\Tag::all());
});

/*
  ROUTE PAR DEFAUT
  PATERN: /
  CTRL: PagesController
  ACTION: show
 */
Route::get('/', 'PagesController@show')->name('accueil');

app/Http/Controllers/TagsController.php
<?php
// ./app/Http/Controllers/CreaturesController.php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\DB;
use App\Http\Models\Tag;

class TagsController extends Controller {
  /**
   * Liste des tags
   * @return [view]      [vue tags/index.blade.php]
   */
  public function index() {
    $tags = Tag::all();
    return View::make('tags.index', compact('tags'));
  }

  /**
   * Détails d'un tag
   * @param  integer $tag [tag de la page à afficher]
   * @return [view]      [vue tags/show.blade.php]
   */
  public function show(Tag $tag) {
    return View::make('tags.show', compact('tag'));
  }
}

resources/views/tags/index.blade.php
{{--
./resources/views/pages/menu.blade.php
Données disponibles :
- $tags: OBJ(id, nom, created_at, updated_at)
--}}
  @foreach ($tags as $tag)
    <li>
      <a href="{{ URL::route('tags.show', [
          'tag'  => $tag->id,
          'slug' => Str::slug($tag->nom)
        ]) }}">
        {{ $tag->nom }}
      </a>
    </li>
  @endforeach

resources/views/tags/show.blade.php
{{--
  ./resources/views/tags/show.blade.php
  variables disponibles :
      - $tag Tag
 --}}
@extends('template.defaut')

@section('titre')
  Créatures du {{ $tag->nom }}
@endsection

@section('contenu')
  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Page Heading -->

        <!-- Title -->
        <h1 class="mt-4">Liste des créatures pour {{ $tag->nom }}</h1>

        <hr>

        @foreach ($tag->creatures as $creature)
          <div class="row">
            <div class="col-md-4">
              <a href="#">
                <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$creature->image) }}" alt="">
              </a>
            </div>
            <div class="col-md-8">
              <h3>{{ $creature->nom }}</h3>
              <p class="lead">
                dans
                <a href="{{ URL::route('films.show', ['film' => $creature->filmData->id, 'slug' => Str::slug($creature->filmData->titre, '-')]) }}">{{ $creature->filmData->titre }}</a> le {{ \Carbon\Carbon::parse($creature->created_at)->format('D d M y') }}
              </p>
              <p>{{ Str::words($creature->texteLead, 20, ' ...') }}</p>
              <a class="btn btn-primary" href="{{ URL::route('creatures.show', ['creature' => $creature->id, 'slug' => Str::slug($creature->nom, '-')]) }}">Voir la créature</a>
              <hr/>
              <ul class="list-inline tags">
                @foreach ($creature->tags as $tag)
                  <li>
                    <a href="{{ route('tags.show', [
                                      'tag'  => $tag->id,
                                      'slug' => Str::slug($tag->nom, '-')
                                      ])}}"class="btn btn-default btn-xs">
                             {{ $tag->nom }}</a>
                  </li>
                @endforeach
              </ul>


      </div>
      </div>
      <hr>
      @endforeach
    </div>

@endsection