routes/web.php
<?php
/*
  ./routes/web.php
  Routeur
*/


/*-----------------------------------
    CREATURES
-----------------------------------*/

Route::prefix('creatures')->name('creatures.')->group(function(){
  /*
    DETAILS D'UNE CREATURE
    PATERN: /creatures/{creature}/{slug}.html
    CTRL: CreaturesController
    ACTION: show
   */
  Route::get('{creature}/{slug}.html', 'CreaturesController@show')
         ->where([
                  'creature'   => '[1-9][0-9]*',
                  'slug' => '[a-z0-9][a-z0-9\-]*'
                ])
         ->name('show');

  /*
    RECHERCHE D'UNE CREATURE
    PATERN: /creatures/search
    CTRL: CreaturesController
    ACTION: search
   */
  Route::get('search', 'CreaturesController@search')->name('search');

});


/*-----------------------------------
    FILMS
-----------------------------------*/
Route::prefix('films')->name('films.')->group(function(){
/*
  DETAILS D'UN FILM
  PATTERN: /films/{film}/{slug}.html [GET]
  CTRL: Films
  ACTION: show
 */
Route::get('{film}/{slug}.html', 'FilmsController@show')
      ->where([
               'film'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('show');

/*
  FORMULAIRE D'AJOUT D'UN FILM
  PATTERN: /films/add [GET]
  CTRL: Films
  ACTION: add
 */
  Route::get('add','FilmsController@add')->name('add');

/*
  AJOUT D'UN FILM
  PATTERN: /films [POST]
  CTRL: Films
  ACTION: store
 */
Route::post('', 'FilmsController@store')->name('store');

/*
  EDITION D'UN FILM
  PATTERN: /films/{film}/{slug}/edit.html    [POST]
  CTRL: Films
  ACTION: edit
 */
Route::get('{film}/{slug}/edit.html', 'FilmsController@edit')
        ->where([
          'film' => '[1-9][0-9]*',
          'slug' => '[a-z0-9][a-z0-9\-]*'
        ])
        ->name('edit');

/*
  UPDATE D'UN FILM
  PATTERN: /films/id/slug.html [PATCH]
  CTRL: Films
  ACTION: update
 */
 Route::patch('/films/{film}/{slug}.html','FilmsController@update')
          ->where([
             'film' => '[1-9][0-9]*',
             'slug' => '[a-z0-9][a-z0-9\-]*'
            ])
         ->name('update');
/*
SUPPRESSION D'UN FILM
 PATTERN: /films/{film}/{slug} [DELETE]
 CTRL: Films
 ACTION: destroy
*/
Route::delete('/films/{film}/{slug}.html', 'FilmsController@destroy')
      ->where([
         'film' => '[1-9][0-9]*',
         'slug' => '[a-z0-9][a-z0-9\-]*'
        ])
      ->name('destroy');
});

/*-----------------------------------
    TAGS
-----------------------------------*/
/*
  DETAILS D'UN TAG
  PATTERN: /tags/{tag}/{slug}.html [GET]
  CTRL: Tags
  ACTION: show
 */
Route::get('/tags/{tag}/{slug}.html', 'TagsController@show')
      ->where([
               'tag'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('tags.show');

/*-----------------------------------
    PAGES
-----------------------------------*/
/*
 DETAILS D'UNE PAGE
 PATERN: /pages/{page}/{slug}.html
 CTRL: PagesController
 ACTION: show
*/
Route::get('/pages/{page}/{slug}.html', 'PagesController@show')
     ->where([
               'page'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('pages.show');

//==============================================================

/*
  MISE A DISPOSITION DE DONNEES POUR CERTAINES VUES
*/
View::composer('pages.menu', function($view){
  $view->with('pages', App\Http\Models\Page::all());
});

View::composer('tags.index', function($view){
  $view->with('tags', App\Http\Models\Tag::all());
});

/*
  ROUTE PAR DEFAUT
  PATERN: /
  CTRL: PagesController
  ACTION: show
 */
Route::get('/', 'PagesController@show')->name('accueil');

resources/views/template/partials/_aside.blade.php
{{--
./resources/views/template/partials/_aside.blade.php
--}}

<!-- Sidebar Widgets Column -->
<div class="col-md-4">

  <form action="{{ URL::route('creatures.search') }}" method="GET" role="search">
    {{ csrf_field() }}
    <!-- Search Widget -->
    <div class="card my-4">
      <h5 class="card-header">Rechercher une créature</h5>
      <div class="card-body">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Mot-clé" name="query" value="{{ request()->input('query') }}">
          <span class="input-group-btn">
            <button class="btn btn-secondary" type="submit">Go!</button>
          </span>
        </div>
      </div>
    </div>
</form>

  <!-- Categories Widget -->
  <div class="card my-4">
    <h5 class="card-header">Tags</h5>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-12">

          <ul class="list-unstyled mb-0">
            @include('tags.index')
          </ul>
        </div>

      </div>
    </div>
  </div>

</div>

resources/views/template/partials/_footer.blade.php
{{--
./resources/views/template/partials/_footer.blade.php
--}}

<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; IEPS 2019 <!-- | <a href="login.html">Administration</a>--></p>
  </div>
  <!-- /.container -->
</footer>

resources/views/template/partials/_head.blade.php
{{--
./resources/views/template/partials/_head.blade.php
--}}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Vintage Sci-Fi - @yield('titre')</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{{ asset('css/blog-post.css') }}" rel="stylesheet">

</head>

resources/views/template/partials/_navigation.blade.php
{{--
./resources/views/template/partials/_navigation.blade.php
--}}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{{ URL::route('accueil') }}">Vintage Sci-Fi - Les Créatures du Futur</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      @include('pages.menu')
    </div>
  </div>
</nav>

resources/views/template/partials/_scripts.blade.php
{{--
./resources/views/template/partials/_scripts.blade.php
--}}

<!-- Bootstrap core JavaScript -->
<script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>