routes/web.php
<?php
/*
  ./routes/web.php
  Routeur
*/


/*-----------------------------------
    CREATURES
-----------------------------------*/

Route::prefix('creatures')->name('creatures.')->group(function(){
  /*
    DETAILS D'UNE CREATURE
    PATERN: /creatures/{creature}/{slug}.html
    CTRL: CreaturesController
    ACTION: show
   */
  Route::get('{creature}/{slug}.html', 'CreaturesController@show')
         ->where([
                  'creature'   => '[1-9][0-9]*',
                  'slug' => '[a-z0-9][a-z0-9\-]*'
                ])
         ->name('show');

  /*
    RECHERCHE D'UNE CREATURE
    PATERN: /creatures/search
    CTRL: CreaturesController
    ACTION: search
   */
  Route::get('search', 'CreaturesController@search')->name('search');

});


/*-----------------------------------
    FILMS
-----------------------------------*/
Route::prefix('films')->name('films.')->group(function(){
/*
  DETAILS D'UN FILM
  PATTERN: /films/{film}/{slug}.html [GET]
  CTRL: Films
  ACTION: show
 */
Route::get('{film}/{slug}.html', 'FilmsController@show')
      ->where([
               'film'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('show');

/*
  FORMULAIRE D'AJOUT D'UN FILM
  PATTERN: /films/add [GET]
  CTRL: Films
  ACTION: add
 */
  Route::get('add','FilmsController@add')->name('add');

/*
  AJOUT D'UN FILM
  PATTERN: /films [POST]
  CTRL: Films
  ACTION: store
 */
Route::post('', 'FilmsController@store')->name('store');

/*
  EDITION D'UN FILM
  PATTERN: /films/{film}/{slug}/edit.html    [POST]
  CTRL: Films
  ACTION: edit
 */
Route::get('{film}/{slug}/edit.html', 'FilmsController@edit')
        ->where([
          'film' => '[1-9][0-9]*',
          'slug' => '[a-z0-9][a-z0-9\-]*'
        ])
        ->name('edit');

/*
  UPDATE D'UN FILM
  PATTERN: /films/id/slug.html [PATCH]
  CTRL: Films
  ACTION: update
 */
 Route::patch('/films/{film}/{slug}.html','FilmsController@update')
          ->where([
             'film' => '[1-9][0-9]*',
             'slug' => '[a-z0-9][a-z0-9\-]*'
            ])
         ->name('update');
/*
SUPPRESSION D'UN FILM
 PATTERN: /films/{film}/{slug} [DELETE]
 CTRL: Films
 ACTION: destroy
*/
Route::delete('/films/{film}/{slug}.html', 'FilmsController@destroy')
      ->where([
         'film' => '[1-9][0-9]*',
         'slug' => '[a-z0-9][a-z0-9\-]*'
        ])
      ->name('destroy');
});

/*-----------------------------------
    TAGS
-----------------------------------*/
/*
  DETAILS D'UN TAG
  PATTERN: /tags/{tag}/{slug}.html [GET]
  CTRL: Tags
  ACTION: show
 */
Route::get('/tags/{tag}/{slug}.html', 'TagsController@show')
      ->where([
               'tag'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('tags.show');

/*-----------------------------------
    PAGES
-----------------------------------*/
/*
 DETAILS D'UNE PAGE
 PATERN: /pages/{page}/{slug}.html
 CTRL: PagesController
 ACTION: show
*/
Route::get('/pages/{page}/{slug}.html', 'PagesController@show')
     ->where([
               'page'   => '[1-9][0-9]*',
               'slug' => '[a-z0-9][a-z0-9\-]*'
             ])
      ->name('pages.show');

//==============================================================

/*
  MISE A DISPOSITION DE DONNEES POUR CERTAINES VUES
*/
View::composer('pages.menu', function($view){
  $view->with('pages', App\Http\Models\Page::all());
});

View::composer('tags.index', function($view){
  $view->with('tags', App\Http\Models\Tag::all());
});

/*
  ROUTE PAR DEFAUT
  PATERN: /
  CTRL: PagesController
  ACTION: show
 */
Route::get('/', 'PagesController@show')->name('accueil');

app/Http/Controllers/FilmsController.php
<?php
// ./app/Http/Controllers/FilmsController.php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Http\Models\Film;
use Illuminate\Support\Facades\View;
use Illuminate\Http\Request;

class FilmsController extends Controller {
  /**
   * Détails d'un film
   * @param  integer $film [film à afficher]
   * @return [view]      [vue films/show.blade.php]
   */
  public function show(Film $film) {
    return View::make('films.show', compact('film'));
  }

    /**
     * Formulaire d'ajout d'un film
     * @return [view]      [vue films/add.blade.php]
     */
  public function add(){
    return View::make('films.add');
  }

  /**
   * Ajout du film
   * @return [view]      [vue pages/show.blade.php]
   */
  public function store(Request $request){
    Film::create($request->all());
  return redirect()->route('pages.show', ['page' => 2, 'slug' => 'les-films']);
  }

  /**
   * Suppression d'un film
   * @param  integer $film [film à supprimer]
   * @return [view]      [vue pages/show.blade.php]
   */
  public function destroy(Film $film){
    $film->destroy($film->id);
    return redirect()->route('pages.show', ['page' => 2, 'slug' => 'les-films']);
  }

  /**
   * Edition d'un film
   * @param  integer $film [film à éditer]
   * @return [view]      [vue films/edit.blade.php]
   */
  public function edit(Film $film){
  return View::make('films.edit', compact('film'));
  }

  /**
   * [update description]
   * @param  Request $request [request]
   * @param  Film    $film    [film à actualiser]
   * @return [view]           [vue pages/show.blade.php]
   */
  public function update(Request $request, Film $film){
  $film->update($request->all());
  return redirect()->route('pages.show', ['page' => 2, 'slug' => 'les-films']);
  }
}

resources/views/films/add.blade.php
{{--
./resources/views/films/add.blade.php
Description: Ajout d'un film
Variables disponibles :
  - $films : Array(OBJ(id, titre, synopsis, created_at, updated_at, image))
--}}
@extends('template.defaut')

@section('titre')
  Ajouter un film
@endsection

@section('contenu')

<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">
      <h1 class="mt-4">Ajouter un Film</h1>

      <form method="POST" action="{{ route('films.store') }}">
        @csrf
        <div class="form-group">
          <label for="">Titre</label>
          <input type="text" class="form-control" name="titre"/>
        </div>
        <div class="form-group">
          <label for="">Synopsis</label>
          <textarea rows="8" cols="80" class="form-control" name="synopsis"></textarea>
        </div>
        <div class="form-group">
          <input type="submit" class="btn btn-primary" />
        </div>
      </form>

      <!-- /.row -->
      <hr>
    </div>
@endsection

resources/views/films/edit.blade.php
{{--
./resources/views/films/add.blade.php
Description: Ajout d'un film
Variables disponibles :
  - $films : Array(OBJ(id, titre, synopsis, created_at, updated_at, image))
--}}
@extends('template.defaut')

@section('titre')
  Ajouter un film
@endsection

@section('contenu')

<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">
      <h1 class="mt-4">Modifier un Film</h1>

      <form method="POST" action="{{ URL::route('films.update', ['film' => $film->id, 'slug' => Str::slug($film->titre, '-')]) }}">
        @csrf
        {{ method_field('PATCH') }}
        <div class="form-group">
          <label for="">Titre</label>
          <input type="text" class="form-control" name="titre" value="{{ $film->titre }}"/>
        </div>
        <div class="form-group">
          <label for="">Synopsis</label>
          <textarea rows="8" cols="80" class="form-control" name="synopsis">{{ $film->synopsis }}</textarea>
        </div>
        <div class="form-group">
          <input type="submit" class="btn btn-primary" />
        </div>
      </form>

      <!-- /.row -->
      <hr>
    </div>
@endsection

resources/views/films/index.blade.php
{{--
./resources/views/films/index.blade.php
Description: Liste des films
Variables disponibles :
  - $films : Array(OBJ(id, titre, synopsis, created_at, updated_at, image))
--}}
<a class="btn btn-primary" href="{{ URL::route('films.add') }}">Ajouter un film</a>
<hr/>
@foreach ($films as $film)
  <div class="row">
    <div class="col-md-4">
      <a href="#">
        <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$film->image) }}" alt="">
      </a>
    </div>
    <div class="col-md-8">
      <h3>{{ $film->titre }}</h3>
      <p>{{ Str::words($film->synopsis, 50, ' ...') }}</p>
      <a class="btn btn-primary" href="{{ URL::route('films.show', ['film' => $film->id, 'slug' => Str::slug($film->titre, '-')]) }}">Voir les détails du film</a>
    </div>
  </div>
  <hr/>
@endforeach

resources/views/films/show.blade.php
{{--
./resources/views/films/show.blade.php
Description: Détails d'un film
Données disponibles :
 - $film : OBJ(id, titre, synopsis, created_at, updated_at, image)
  -
--}}
@extends('template.defaut')

@section('titre')
  {{ $film->titre }}
@stop

@section('contenu')
  <!-- Page Content -->
  <div class="container">

    <div class="row">
  <!-- Post Content Column -->
  <div class="col-lg-8">

    <!-- Page Heading -->

    <!-- Title -->
    <h1 class="mt-4">{{ $film->titre }}</h1>

    <hr>

    <!-- Project One -->
    <div class="row">
      <div class="col-md-4">
        <a href="#">
          <img class="img-fluid rounded mb-3 mb-md-0" src="{{ asset('images/'.$film->image) }}" alt="">
        </a>
      </div>
      <div class="col-md-8">
        <p class="lead">{{ $film->synopsis }}</p>
        <hr/>
        <h2>Créatures du film</h2>
        <ul>
          @foreach ($film->creatures as $creature)
            <li><a href="{{ URL::route('creatures.show', ['creature'  => $creature->id,'slug' => Str::slug($creature->nom, '-')])}}">{{ $creature->nom }}</a></li>
          @endforeach
        </ul>
        <hr/>
          <a class="btn btn-primary" href="{{ URL::route('films.edit', ['film' => $film->id, 'slug' => Str::slug($film->titre, '-')]) }}">Modifier</a>
          <form method="POST" style="display: inline-block;" action="{{ route('films.destroy', ['film' => $film->id, 'slug' => Str::slug($film->titre, '-')]) }}">
            {{ csrf_field() }}
            {{ method_field('DELETE') }}
            <div class="form-group">
              <input type="submit" class="btn btn-secondary" value="Delete">
            </div>
          </form>
        <hr/>

      </div>
    </div>
    <!-- /.row -->
    <hr>
  </div>
@stop